### ISSUE TITLE
Random crash on stage load

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sa2-battle-network#10] opened 2016-01-22 17:17 UTC
Happens ~~most consistently~~ only in Emerald Hunting, and usually only happens on the client... ~~and only without the Visual Studio debugger attached. Works with IDA though.~~

Either way, it's a null reference, and is likely related to actions being set too soon, so the game expects data to be somewhere that it isn't.

This is almost certainly caused by the current Emerald synchronization method.

**Comment by SonicFreak94** [comment] 2016-04-04 07:11
Fixed by 0b2058900b84949c07663f22ec3f5644d07e8156

**Comment by SonicFreak94** [comment] 2016-04-05 01:07
Or not. Happened with Knuckles and Tikal in Death Chamber.

**Comment by SonicFreak94** [comment] 2016-04-10 02:55
This is almost certainly caused by emerald synchronization.

**Closed as completed** 2016-04-12 05:27 UTC
Labels: bug
